directories:
  output: dist-electron
  buildResources: build
appId: com.mooderia.app
productName: The Mooderia
files:
  - filter:
      - dist/**/*
      - electron/main.js
win:
  target: portable
electronVersion: 30.5.1
